version: "2"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      # The API for InfluxDB is served on port 8086
      - "${INFLUX_PORT_1}:8086"
      - "${INFLUX_PORT_2}:8082"
    environment:
      - INFLUXDB_DB=otlink
      - INFLUXDB_USER=otlink
      - INFLUXDB_USER_PASSWORD=${DB_PASSWORD}
      - INFLUXDB_ADMIN_USER=influxadmin
      - INFLUXDB_ADMIN_PASSWORD=${INFLUX_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    ports:
      - "${TELEGRAF_PORT_1}:8092/udp"
      - "${TELEGRAF_PORT_2}:8094"
      - "${TELEGRAF_PORT_3}:8125/udp"
    environment:
      - INFLUX_USERNAME=influxadmin
      - INFLUX_PASSWORD=${INFLUX_ADMIN_PASSWORD}
      - INFLUX_URL=http://influxdb:8086 
      - HOST_PROC=/rootfs/proc
      - HOST_SYS=/rootfs/sys
      - HOST_ETC=/rootfs/etc
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/rootfs/sys:ro
      - /proc:/rootfs/proc:ro
      - /etc:/rootfs/etc:ro      
      
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "${CHRONOGRAF_PORT_1}:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=influxadmin
      - INFLUXDB_PASSWORD=${INFLUX_ADMIN_PASSWORD}
      - KAPACITOR_URL=http://kapacitor:9092
      - AUTH_DURATION=0
    depends_on:
      - influxdb
      
  kapacitor:
    image: kapacitor:latest
    container_name: kapacitor
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "${KAPACITOR_PORT_1}:9092"
    environment:
      - KAPACITOR_HOSTNAME=kapacitor
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_INFLUXDB_0_USERNAME=influxadmin
      - KAPACITOR_INFLUXDB_0_PASSWORD=${INFLUX_ADMIN_PASSWORD}
    depends_on:
      - influxdb
      
  postgres:
    image: postgres:9.6.5
    restart: "always"
    environment:
      - POSTGRES_DB=hydra
      - POSTGRES_USER=hydrauser
      - POSTGRES_PASSWORD=hydrapassword
    ports:
      - 5432:5432/tcp
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    network_mode: bridge

volumes:
  postgres-vol:
    driver: local

