version: "2"

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      # The API for InfluxDB is served on port 8086
      - "${INFLUX_PORT_1}:8086"
      - "${INFLUX_PORT_2}:8082"
    environment:
      - INFLUXDB_DB=otlink
      - INFLUXDB_ADMIN_USER=otlink
      - INFLUXDB_ADMIN_PASSWORD=${DB_PASSWORD}
      
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    ports:
      - "${TELEGRAF_PORT_1}:8092/udp"
      - "${TELEGRAF_PORT_2}:8094"
      - "${TELEGRAF_PORT_3}:8125/udp"
      
  chronograf:
    image: chronograf:latest
    container_name: chronograf
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "${CHRONOGRAF_PORT_1}:8888"
    depends_on:
      - influxdb
      
  kapacitor:
    image: kapacitor:latest
    container_name: kapacitor
    ports:
      # The WebUI for Chronograf is served on port 8888
      - "${KAPACITOR_PORT_1}:9092"
    environment:
      - KAPACITOR_HOSTNAME=kapacitor
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    depends_on:
      - influxdb
