version: "3"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      # The API for InfluxDB is served on port 8086
      - "8088:8088"
      - "8082:8082"
    environment:
      - INFLUXDB_DB=influxdb
      - INFLUXDB_ADMIN_USER=telegraf
      - INFLUXDB_ADMIN_PASSWORD=telegraf

